export const newsData = [
  {
    title: 'Justin Wong TV FT. DR.B - "Beat A Boss Challenge"',
    href: "https://www.youtube.com/watch?v=zumPZvp1Hdk&t",
    image: "/NewsImages/News3.png",
    alt: "News1",
    description: `Check out this video showcasing our team member Galaxy B as they take on the exhilarating "Beat A Boss Challenge" alongside the legendary Justin Wong at EVO 2023! Don't miss out on the action – watch the video now!`,
    className: "text-primary underline",
  },
  {
    title: "Evo Japan 2023 interview FT. Dr.B",
    href: "https://www.youtube.com/watch?v=J7-SwpBReEg&t",
    image: "/NewsImages/News1.png",
    alt: "News2",
    description: `Check out this interview as Galaxy B recounts the thrilling journey, offering a glimpse into the challenges faced, victories achieved, and the overall excitement of their time at EVO Japan.`,
    className: "text-accent underline",
  },
  {
    title: "StrikeFirst On Button Check Pt. 2 FT. Cookye",
    href: "https://www.youtube.com/watch?v=hAjRZM6yGMQ",
    image: "/NewsImages/News2.png",
    alt: "News3",
    description: `Our very own Cookye Fu Sung has been featured on button check. Delve into the narrative of Cookye's passion and prowess on display at this prestigious event – press play now for an exclusive peek into her adventure!`,
    className: "text-secondary underline",
  },
  {
    title: "Hollywood Rob TV interview by DR.B",
    href: "https://www.youtube.com/watch?v=xX7qFzNflmI",
    image: "/NewsImages/News4.png",
    alt: "News4",
    description: `Get the inside scoop as Hollywood Rob TV goes one-on-one with DR.B aka GALAXY B at the world's biggest fighting game tournament.`,
    className: "text-primary underline",
  },
  {
    title: "Okplayer interview with DR.B aka GALAXY B at Defend The North X",
    href: "https://www.youtube.com/watch?v=OJ0WxjF4mCU",
    image: "/NewsImages/News5.png",
    alt: "News5",
    description: `Hip-hop meets the FGC as Okplayer catches up with DR.B aka GALAXY B at 2024's most electrifying tournament. From the culture to the competition, discover what drives one of the scene's most dynamic voices.`,
    className: "text-accent underline",
  },
  {
    title: "Okplayer interview with DR.B aka GALAXY B at Defend The North X",
    href: "https://www.youtube.com/watch?v=eIhkPEgZpI4",
    image: "/NewsImages/News6.png",
    alt: "News6",
    description: `Witness legendary moments that never made it to the main stream. Uncover explosive bracket matches, clutch comebacks, and jaw-dropping tech from CvS2's greatest EVO showdowns.`,
    className: "text-secondary underline",
  },
];
